defaults: &defaults
  docker:
    - image: wscandy/ci-docker
  working_directory: ~/repo
  environment:
    IMAGE: "ci-docker"

version: 2
jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Build Images
          command: |
              docker build -t $DOCKERHUB_USER/$IMAGE .
  build_tagged:
    <<: *defaults
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Build Images
          command: |
              mkdir -p docker_cache
              docker build -t $DOCKERHUB_USER/$IMAGE:$CIRCLE_TAG -t $DOCKERHUB_USER/$IMAGE .
              docker save -o docker_cache/$CIRCLE_TAG.tar $DOCKERHUB_USER/$IMAGE:$CIRCLE_TAG
              docker save -o docker_cache/$IMAGE.tar $DOCKERHUB_USER/$IMAGE
      - persist_to_workspace:
          root: .
          paths:
            - docker_cache
  push:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/repo
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Push Images
          command: |
              docker login -u $DOCKERHUB_USER -p $DOCKERHUB_PASSWORD
              docker load < docker_cache/$CIRCLE_TAG.tar
              docker push $DOCKERHUB_USER/$IMAGE:$CIRCLE_TAG
              docker load < docker_cache/$IMAGE.tar
              docker push $DOCKERHUB_USER/$IMAGE

workflows:
  version: 2
  build:
    jobs:
      - build:
          context: wscandy
  build_deploy:
    jobs:
      - build_tagged:
          context: wscandy
          filters:
            tags:
              only: /.*/
            branches:
              ignore: /.*/
      - push:
          context: wscandy
          requires:
            - build_tagged
          filters:
            tags:
              only: /.*/
            branches:
              ignore: /.*/